### ISSUE TITLE
Incompatible with zio-prelude:1.0.0-RC3

### ISSUE THREAD

**Issue by adrianfilip** [kitlangton/zio-magic#41]
If I have 
"dev.zio"  %% "zio-prelude"  % "1.0.0-RC3" 
in my dependencies it fails with the below error. 

The scala version used is 2.13.4.

This doesn't happen with RC1.

`scalac: Error: 'zio.prelude.TraversableSyntax$TraversableOps zio.prelude.package$.TraversableOps(java.lang.Object)'
java.lang.NoSuchMethodError: 'zio.prelude.TraversableSyntax$TraversableOps zio.prelude.package$.TraversableOps(java.lang.Object)'
	at zio.magic.macros.graph.Graph.buildComplete(Graph.scala:14)
	at zio.magic.macros.utils.ExprGraphSupport$ExprGraph.buildLayerFor(ExprGraphSupport.scala:19)
	at zio.magic.macros.ProvideMagicLayerMacro.provideCustomMagicLayerImpl(ProvideMagicLayerMacro.scala:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at scala.reflect.macros.runtime.JavaReflectionRuntimes$JavaReflectionResolvers.$anonfun$resolveJavaReflectionRuntime$5(JavaReflectionRuntimes.scala:45)
	at scala.tools.nsc.typechecker.Macros.macroExpandWithRuntime(Macros.scala:770)
	at scala.tools.nsc.typechecker.Macros.macroExpandWithRuntime$(Macros.scala:746)
	at scala.tools.nsc.Global$$anon$5.macroExpandWithRuntime(Global.scala:484)
	at scala.tools.nsc.typechecker.Macros$MacroExpander.$anonfun$expand$1(Macros.scala:576)
	at scala.tools.nsc.Global.withInfoLevel(Global.scala:228)
	at scala.tools.nsc.typechecker.Macros$MacroExpander.expand(Macros.scala:569)
	at scala.tools.nsc.typechecker.Macros$MacroExpander.apply(Macros.scala:556)
	at scala.tools.nsc.typechecker.Macros.standardMacroExpand(Macros.scala:731)
	at scala.tools.nsc.typechecker.Macros.standardMacroExpand$(Macros.scala:729)
	at scala.tools.nsc.Global$$anon$5.standardMacroExpand(Global.scala:484)
	at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$10.default(AnalyzerPlugins.scala:456)
	at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$10.default(AnalyzerPlugins.scala:453)
	at scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:410)
	at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand(AnalyzerPlugins.scala:453)
	at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand$(AnalyzerPlugins.scala:453)
	at scala.tools.nsc.Global$$anon$5.pluginsMacroExpand(Global.scala:484)
	at scala.tools.nsc.typechecker.Macros.macroExpand(Macros.scala:720)
	at scala.tools.nsc.typechecker.Macros.macroExpand$(Macros.scala:713)
	at scala.tools.nsc.Global$$anon$5.macroExpand(Global.scala:484)
	at scala.tools.nsc.typechecker.Typers$Typer.vanillaAdapt$1(Typers.scala:1205)
	at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1273)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6008)
	at scala.tools.nsc.typechecker.Typers$Typer.typedSelectOrSuperCall$1(Typers.scala:6091)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5937)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5993)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$41(Typers.scala:5038)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:694)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:5040)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:5068)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5936)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5993)
	at scala.tools.nsc.typechecker.Typers$Typer.typedSelectOrSuperCall$1(Typers.scala:6091)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5937)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5993)
	at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:6270)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5901)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5993)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6071)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3403)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3403)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2057)
	at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1933)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5903)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5993)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6071)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3403)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3403)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5598)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5905)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5993)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:117)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:454)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:105)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1515)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1499)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1491)
	at scala.tools.nsc.Global$Run.compileFiles(Global.scala:1605)
	at xsbt.CachedCompiler0.run(CompilerBridge.scala:163)
	at xsbt.CachedCompiler0.run(CompilerBridge.scala:134)
	at xsbt.CompilerBridge.run(CompilerBridge.scala:39)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:89)
	at org.jetbrains.jps.incremental.scala.local.IdeaIncrementalCompiler.compile(IdeaIncrementalCompiler.scala:57)
	at org.jetbrains.jps.incremental.scala.local.LocalServer.compile(LocalServer.scala:43)
	at org.jetbrains.jps.incremental.scala.remote.Main$.compileLogic(Main.scala:158)
	at org.jetbrains.jps.incremental.scala.remote.Main$.$anonfun$handleCommand$1(Main.scala:141)
	at org.jetbrains.jps.incremental.scala.remote.Main$.decorated$1(Main.scala:131)
	at org.jetbrains.jps.incremental.scala.remote.Main$.handleCommand(Main.scala:138)
	at org.jetbrains.jps.incremental.scala.remote.Main$.serverLogic(Main.scala:115)
	at org.jetbrains.jps.incremental.scala.remote.Main$.nailMain(Main.scala:71)
	at org.jetbrains.jps.incremental.scala.remote.Main.nailMain(Main.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
`

**Comment by kitlangton** [comment]
Yeah, some things I was using in Prelude have changed :'(

**Comment by kitlangton** [comment]
I actually don't need the dependency. I'll copy my implementation over from the ZIO 2.0 branch once that's public—should be within a week or so?

**Comment by kitlangton** [comment]
Or, of course, a PR is welcome :) I just have to buckle down on the 2.0 changes at the moment.

**Comment by adrianfilip** [comment]
I'll give it a shot.  :)

**Comment by kitlangton** [comment]
Looks like RC-3 just came out, so says the Scala Steward. Perhaps that's easier to integrate?

**Comment by adrianfilip** [comment]
I saw that and am using RC3 for the integration.  I'll change the title of the ticket to avoid confusion.
I think the code changes are done but some tests are failing so I have to look into that a bit.

**Comment by kitlangton** [comment]
I've actually back ported my implementation from ZIO 2.0, which doesn't have any dependencies on prelude :) So huzzah!
